// <auto-generated />
using System;
using ExamAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExamAPI.Migrations
{
    [DbContext(typeof(ExamAPIContext))]
    partial class ExamAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExamAPI.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerOptions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CorrectAnswers")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("ExamAPI.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_of_Exam")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExamsId")
                        .HasColumnType("integer");

                    b.Property<int>("Grade_Exam")
                        .HasColumnType("integer");

                    b.Property<string>("Name_Exam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuesttionId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamsId");

                    b.HasIndex("QuesttionId");

                    b.HasIndex("UserId");

                    b.ToTable("Exam");
                });

            modelBuilder.Entity("ExamAPI.Models.Exams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name_exam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("ExamAPI.Models.ExamsTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamsId")
                        .HasColumnType("integer");

                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamsId");

                    b.HasIndex("TestId");

                    b.ToTable("ExamsTest");
                });

            modelBuilder.Entity("ExamAPI.Models.Filles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Name")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Filles");
                });

            modelBuilder.Entity("ExamAPI.Models.Options", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_AnswerId")
                        .HasColumnType("integer");

                    b.Property<int>("Id_TestId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionsId")
                        .HasColumnType("integer");

                    b.Property<int>("Questions_IdId")
                        .HasColumnType("integer");

                    b.Property<string>("Test_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id_AnswerId");

                    b.HasIndex("Id_TestId");

                    b.HasIndex("QuestionsId");

                    b.HasIndex("Questions_IdId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("ExamAPI.Models.QuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("integer");

                    b.Property<string>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionsId");

                    b.ToTable("QuestionAnswer");
                });

            modelBuilder.Entity("ExamAPI.Models.Questions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerTrue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("ExamAPI.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name_roles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ExamAPI.Models.Save_results", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Date_of_Result_Exam_Endings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Exam_idId")
                        .HasColumnType("integer");

                    b.Property<int>("Name_TestId")
                        .HasColumnType("integer");

                    b.Property<string>("Name_Users")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionsId")
                        .HasColumnType("integer");

                    b.Property<int>("Resukts_exam")
                        .HasColumnType("integer");

                    b.Property<int>("User_idId")
                        .HasColumnType("integer");

                    b.Property<string>("Users_Answers_Questions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Exam_idId");

                    b.HasIndex("Name_TestId");

                    b.HasIndex("QuestionsId");

                    b.HasIndex("User_idId");

                    b.ToTable("Save_Results");
                });

            modelBuilder.Entity("ExamAPI.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name_Test")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Options_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("ExamAPI.Models.TestQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdQuestionsId")
                        .HasColumnType("integer");

                    b.Property<int>("IdTestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdQuestionsId");

                    b.HasIndex("IdTestId");

                    b.ToTable("TestQuestion");
                });

            modelBuilder.Entity("ExamAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DataMess")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmailId")
                        .HasColumnType("integer");

                    b.Property<string>("Employee_Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_roles_users")
                        .HasColumnType("integer");

                    b.Property<string>("Name_Employee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmailId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExamAPI.Models.UserExams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamsId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamsId");

                    b.HasIndex("UserId");

                    b.ToTable("UserExams");
                });

            modelBuilder.Entity("ExamAPI.Models.User_roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_rolesId")
                        .HasColumnType("integer");

                    b.Property<int>("User_idId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_rolesId");

                    b.HasIndex("User_idId");

                    b.ToTable("User_Roles");
                });

            modelBuilder.Entity("ExamAPI.Models.Exam", b =>
                {
                    b.HasOne("ExamAPI.Models.Exams", "Exams")
                        .WithMany()
                        .HasForeignKey("ExamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamAPI.Models.Questions", "Questtion")
                        .WithMany()
                        .HasForeignKey("QuesttionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exams");

                    b.Navigation("Questtion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExamAPI.Models.ExamsTest", b =>
                {
                    b.HasOne("ExamAPI.Models.Exams", "Exams")
                        .WithMany()
                        .HasForeignKey("ExamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamAPI.Models.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exams");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("ExamAPI.Models.Options", b =>
                {
                    b.HasOne("ExamAPI.Models.Answer", "Id_Answer")
                        .WithMany()
                        .HasForeignKey("Id_AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamAPI.Models.Test", "Id_Test")
                        .WithMany()
                        .HasForeignKey("Id_TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamAPI.Models.Questions", "Questions")
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamAPI.Models.Questions", "Questions_Id")
                        .WithMany()
                        .HasForeignKey("Questions_IdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Id_Answer");

                    b.Navigation("Id_Test");

                    b.Navigation("Questions");

                    b.Navigation("Questions_Id");
                });

            modelBuilder.Entity("ExamAPI.Models.QuestionAnswer", b =>
                {
                    b.HasOne("ExamAPI.Models.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamAPI.Models.Questions", "Questions")
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ExamAPI.Models.Save_results", b =>
                {
                    b.HasOne("ExamAPI.Models.Exams", "Exam_id")
                        .WithMany()
                        .HasForeignKey("Exam_idId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamAPI.Models.Test", "Name_Test")
                        .WithMany()
                        .HasForeignKey("Name_TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamAPI.Models.Questions", "Questions")
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamAPI.Models.User", "User_id")
                        .WithMany()
                        .HasForeignKey("User_idId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam_id");

                    b.Navigation("Name_Test");

                    b.Navigation("Questions");

                    b.Navigation("User_id");
                });

            modelBuilder.Entity("ExamAPI.Models.TestQuestion", b =>
                {
                    b.HasOne("ExamAPI.Models.Questions", "IdQuestions")
                        .WithMany()
                        .HasForeignKey("IdQuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamAPI.Models.Test", "IdTest")
                        .WithMany()
                        .HasForeignKey("IdTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdQuestions");

                    b.Navigation("IdTest");
                });

            modelBuilder.Entity("ExamAPI.Models.User", b =>
                {
                    b.HasOne("ExamAPI.Models.Filles", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("ExamAPI.Models.UserExams", b =>
                {
                    b.HasOne("ExamAPI.Models.Exams", "Exams")
                        .WithMany()
                        .HasForeignKey("ExamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exams");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExamAPI.Models.User_roles", b =>
                {
                    b.HasOne("ExamAPI.Models.Roles", "Id_roles")
                        .WithMany()
                        .HasForeignKey("Id_rolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamAPI.Models.User", "User_id")
                        .WithMany()
                        .HasForeignKey("User_idId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Id_roles");

                    b.Navigation("User_id");
                });
#pragma warning restore 612, 618
        }
    }
}
